gcr.io support, regexp tags and multiply images
wantedly/dockertags pull request #10
Opened 2019-01-10 14:16 UTC by psvmcc

gcr.io support, also works for k8s.gcr.io, private images not tested
regexp tags option
set multiply IMAGENAMES per time

2019-01-11 01:18 UTC, luvtechno commented
Can someone from @wantedly/infrastructure take a look?

2019-01-11 10:36 UTC, bgpat commented
> gcr.io support, also works for k8s.gcr.io, private images not tested

It looks good, although I prefer `gcr` to `gcrio`.

> set multiply IMAGENAMES per time

Why not use `xargs` instead?

2019-01-11 10:37 UTC, koudaiii approved these changes
Thank you for a great job!!
LGTM!!

2019-01-11 14:33 UTC, psvmcc commented
> > gcr.io support, also works for k8s.gcr.io, private images not tested
> 
> It looks good, although I prefer `gcr` to `gcrio`.
I can rename :)

> 
> > set multiply IMAGENAMES per time
> 
> Why not use `xargs` instead?
Because I don't want to fork multiply processes over bash loop, but it works and with `xargs` also.

2019-01-11 14:35 UTC, psvmcc commented
Also fixed quay.io pagination in tag v0.3.1, try execute two versions:
```
v0.2.0: $ dockertags quay.io/calico/cni
v0.3.1: $ dockertags quay.io/calico/cni
```

Results will be different :)

2019-01-12 02:36 UTC, bgpat commented
> regexp tags option

I think you should use other command tools for filtering unless pass the filtering parameter in API request. 

> > > gcr.io support, also works for k8s.gcr.io, private images not tested
> > 
> > It looks good, although I prefer `gcr` to `gcrio`.
> 
> I can rename :)

Please rename 😄 

> > 
> > > set multiply IMAGENAMES per time
> > 
> > Why not use `xargs` instead?
> 
> Because I don't want to fork multiply processes over bash loop, but it works and with `xargs` also.

I don't care about the cost of process forking because that is too small rather than the HTTP request. What do you think?

> Also fixed quay.io pagination

Thanks for your bugfix!!!

2019-01-12 09:08 UTC, psvmcc commented
> > regexp tags option
> 
> I think you should use other command tools for filtering unless pass the filtering parameter in API request.

Yes, its possible to use grep over pipe, but it's can be done with one util, I think its better. Also in my code, I did filtering only on output tags stage, not on API requests to docker registry.

> > > > gcr.io support, also works for k8s.gcr.io, private images not tested
> > > 
> > > 
> > > It looks good, although I prefer `gcr` to `gcrio`.
> > 
> > 
> > I can rename :)
> 
> Please rename 😄

Done :)

> > > > set multiply IMAGENAMES per time
> > > 
> > > 
> > > Why not use `xargs` instead?
> > 
> > 
> > Because I don't want to fork multiply processes over bash loop, but it works and with `xargs` also.
> 
> I don't care about the cost of process forking because that is too small rather than the HTTP request. What do you think?

Pros for my version:
- works both variants, with multiply IMAGENAMES and with one over `xargs`
- if someone need regexp tags, its possible use with only one pipe
 
Cons for my version:
- maybe memory leak on multiply imagesnames requests with hard regexp query

2019-01-12 14:23 UTC, bgpat commented
Our command-line tools are designed by [The Unix philosophy](http://web.mit.edu/6.055/old/S2009/notes/unix.pdf). 

> 1. Small is beautiful.
> 2. Make each program do one thing well.

Your changes go off this philosophy. I want to keep simple interface and implementation. Can you remove regexp feature and multiple IMAGENAMES feature?

2019-01-12 16:40 UTC, psvmcc commented
> Can you remove regexp feature and multiple IMAGENAMES feature?

Ok, done.

2019-01-12 18:31 UTC, bgpat requested changes

2019-01-12 18:31 UTC, bgpat commented on gcr.go
> +func constructgcrURL(image string, grepo string) (string, error) {
```suggestion
func constructGcrURL(image string, grepo string) (string, error) {
```

or 

```suggestion
func constructGCRURL(image string, grepo string) (string, error) {
```

2019-01-12 18:31 UTC, bgpat commented on gcr.go
> +type gcrTag struct {
`gcrTag` is not used anywhere.

2019-01-12 18:31 UTC, bgpat commented on gcr.go
> +	u, err := url.Parse(gcrURLBase)
`u` will be same value anytime because `gcrURLBase` is defined const string. How about constructing the URL object directly?

```go
u := url.URL{
	Scheme: "https",
	Path: path.Join(...),
}
```

2019-01-12 18:31 UTC, bgpat commented on gcr.go
> +func retriveFromgcr(image string, grepo string) ([]string, error) {
```suggestion
func retriveFromGCR(image string, grepo string) ([]string, error) {
```

or 

```suggestion
func retriveFromGcr(image string, grepo string) ([]string, error) {
```

2019-01-12 18:31 UTC, bgpat commented on gcr.go
> +  }
Please fix indent.

2019-01-12 18:31 UTC, bgpat commented on main.go
> +		if strings.Contains(ss[0], "gcr.io") {
In strictly, you should use `string.HasSuffix` instead of `strings.Contains`.

2019-01-12 18:31 UTC, bgpat commented on main.go
> +		grepo = ss[0]
Should `grepo` be extracted in `gcr.go`? I think it's ok to replace existed switch cases:

```go
switch {
	case repo == "hub.docker.com":
		...
	case repo == "quay.io":
		...
	case strings.HasSuffix(repo, "gcr.io"):
		...
}
```

2019-01-12 18:31 UTC, bgpat commented on quay.go
> +  )
Please fix indent with `go fmt`.

2019-01-12 18:31 UTC, bgpat commented on quay.go
> +  	HasAdditional	bool
```suggestion
	hasAdditional	bool
```

2019-01-12 18:31 UTC, bgpat commented on quay.go
> +    Page		int
```suggestion
	page		int
```

2019-01-12 18:31 UTC, bgpat commented on quay.go
> +  Page = 1
Please declare and initialize in one go.

```go
var (
	hasAdditional = true
	page          = 1
	repo          QuayTagsResponse
	tags          []string
)
```

2019-01-12 18:31 UTC, bgpat commented on quay.go
> +func constructQuayURL(image string, Page int) (string, error) {
A private variable should be lowercase.

```suggestion
func constructQuayURL(image string, page int) (string, error) {
```

2020-03-24 20:08 UTC, closed without merging